PATHS:
  CLIPS_TABLE: 'data/clips_by_patient.csv'
  FRAME_TABLE: 'data/frames.csv'   # Path to all LUS frames in the dataset
  FRAMES: 'data/frames/'
  PARTITIONS: 'data/partitions/'
  TEST_DF: 'data/partitions/test_set.csv'
  GEN_IMAGES: 'documents/generated_images/'
  LOGS: 'results/logs/'
  IMAGES: 'results/figures/'
  MODEL_WEIGHTS: 'results/models/'
  MODEL_TO_LOAD: 'results/models/finalmodel.h5'
  CLASS_NAME_MAP: 'data/serializations/output_class_indices.pkl'
  BATCH_PREDS: 'results/predictions/'
  METRICS: './results/metrics/'

DATA:
  IMG_DIM: [128, 128]
  VAL_SPLIT: 0.1
  TEST_SPLIT: 0.1
  CLASSES: ['a_lines', 'b_lines']   # Classes for binary classification

TRAIN:
  MODEL_DEF: 'xception'                               # One of {'vgg16', 'mobilenetv2', 'xception', 'efficientnetb7}
  EXPERIMENT_TYPE: 'single_train'                           # One of {'single_train'}
  N_CLASSES: 2
  BATCH_SIZE: 16
  EPOCHS: 200
  PATIENCE: 10
  METRIC_PREFERENCE: ['auc', 'recall', 'precision', 'loss']
  NUM_GPUS: 1
  MIXED_PRECISION: false                         # Necessary for training with Tensor Cores
  DATA_AUG:
    ZOOM_RANGE: 0.1
    HORIZONTAL_FLIP: true
    WIDTH_SHIFT_RANGE: 0.2
    HEIGHT_SHIFT_RANGE: 0.2
    SHEAR_RANGE: 20
    ROTATION_RANGE: 20
    BRIGHTNESS_RANGE: [0.8, 1.2]

NN:
  MOBILENETV2:
    LR: 0.01
    DROPOUT: 0.5
    L2_LAMBDA: 0.01
    NODES_DENSE0: 32
    FROZEN_LAYERS: []
  SHUFFLENETV2:
    LR: 0.1
    DROPOUT: 0.5
    L2_LAMBDA: 0.01
  VGG16:
    LR: 0.01
    DROPOUT: 0.5
    L2_LAMBDA: 0.01
    NODES_DENSE0: 64
    FROZEN_LAYERS: []
  XCEPTION:
    LR: 0.01
    DROPOUT: 0.5
    FROZEN_LAYERS: []
    L2_LAMBDA: 0.01
  BiTR50x1:
    #https://blog.tensorflow.org/2020/05/bigtransfer-bit-state-of-art-transfer-learning-computer-vision.html
    LR: 0.1
    DROPOUT: 0.5
    L2_LAMBDA: 0.01
  EFFICIENTNETB7:
    LR: 0.1
    DROPOUT: 0.5
    L2_LAMBDA: 0.01
    FROZEN_LAYERS: []