PATHS:
  CLIPS_TABLE: 'data/clips_by_patient.csv'
  FRAME_TABLE: 'data/frames.csv'   # Path to all LUS frames in the dataset
  DATABASE_QUERY: 'data/parenchymal_clips.csv'
  RAW_CLIPS: 'data/raw_clips/'
  FRAMES: 'data/frames/' #'D:\\Documents\\Data\\ab-frames '
  PARTITIONS: 'data/partitions/'
  TEST_DF: 'data/partitions/test_set.csv'
  HEATMAPS: 'img/heatmaps'
  LOGS: 'results/logs/'
  IMAGES: 'results/figures/'
  MODEL_WEIGHTS: 'results/models/'
  MODEL_TO_LOAD: 'results/models/model20210429-193519.h5'
  CLASS_NAME_MAP: 'data/serializations/output_class_indices.pkl'
  BATCH_PREDS: 'results/predictions/'
  METRICS: './results/metrics/'
  EXPERIMENTS: './results/experiments'

DATA:
  IMG_DIM: [112, 112]
  VAL_SPLIT: 0.1
  TEST_SPLIT: 0.1
  CLASSES: ['a_lines', 'b_lines']   # Classes for binary classification

TRAIN:
  MODEL_DEF: 'custom_resnetv2'                      # One of {'vgg16', 'mobilenetv2', 'xception', 'efficientnetb7'}
  EXPERIMENT_TYPE: 'single_train'               # One of {'single_train', 'cross_validation', 'hparam_search'}
  N_CLASSES: 2
  BATCH_SIZE: 64
  EPOCHS: 200
  PATIENCE: 7
  METRIC_PREFERENCE: ['auc', 'recall', 'precision', 'loss']
  NUM_GPUS: 1
  MIXED_PRECISION: false                         # Necessary for training with Tensor Cores
  N_FOLDS: 10
  DATA_AUG:
    ZOOM_RANGE: 0.1
    HORIZONTAL_FLIP: true
    WIDTH_SHIFT_RANGE: 0.2
    HEIGHT_SHIFT_RANGE: 0.2
    SHEAR_RANGE: 10
    ROTATION_RANGE: 45
    BRIGHTNESS_RANGE: [0.7, 1.3]
  HPARAM_SEARCH:
    N_EVALS: 500
    HPARAM_OBJECTIVE: 'auc'

HPARAMS:
  MOBILENETV2:
    LR: 0.001
    DROPOUT: 0.35
    L2_LAMBDA: 0.0001
    NODES_DENSE0: 32
    FROZEN_LAYERS: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,16,17,18,19,20,21,22,23,24,25,26,26,27,28,29,30]
  SHUFFLENETV2:
    LR: 0.1
    DROPOUT: 0.5
    L2_LAMBDA: 0.01
  VGG16:
    LR: 0.01
    DROPOUT: 0.5
    L2_LAMBDA: 0.01
    NODES_DENSE0: 64
    FROZEN_LAYERS: []
  XCEPTION:
    LR: 0.01
    DROPOUT: 0.5
    FROZEN_LAYERS: []
    L2_LAMBDA: 0.01
  BiTR50x1:
    #https://blog.tensorflow.org/2020/05/bigtransfer-bit-state-of-art-transfer-learning-computer-vision.html
    LR: 0.1
    DROPOUT: 0.5
    L2_LAMBDA: 0.01
  EFFICIENTNETB7:
    LR: 0.1
    DROPOUT: 0.5
    L2_LAMBDA: 0.01
    FROZEN_LAYERS: []
  CNN0:
    LR: 0.001
    DROPOUT: 0.35
    L2_LAMBDA: 0.0001
    NODES_DENSE0: 64
    KERNEL_SIZE: (3, 3)
    STRIDES: (1, 1)
    MAXPOOL_SIZE: (2, 2)
    BLOCKS: 4
    INIT_FILTERS: 32
    FILTER_EXP_BASE: 2
  CUSTOM_RESNETV2:
    LR: 0.00001
    DROPOUT: 0.5
    L2_LAMBDA: 0.003
    NODES_DENSE0: 0
    KERNEL_SIZE: (3, 3)
    STRIDES: (1, 1)
    MAXPOOL_SIZE: (2, 2)
    BLOCKS: 1
    INIT_FILTERS: 32

HPARAM_SEARCH:
  MOBILENETV2:
    LR:
      TYPE: 'float_log'
      RANGE: [0.00001, 0.001]
    DROPOUT:
      TYPE: 'float_uniform'
      RANGE: [0.0, 0.5]